categorical_columns:
  Class:
  - Business
  - Eco Plus
  - Eco
  Cleanliness:
  - 4
  - 2
  - 3
  - 1
  - 5
  - 0
  Customer_Type:
  - Loyal Customer
  - disloyal Customer
  Ease_of_Online_booking:
  - 5
  - 2
  - 1
  - 4
  - 3
  - 0
  Inflight_entertainment:
  - 4
  - 2
  - 3
  - 1
  - 5
  - 0
  Inflight_wifi_service:
  - 5
  - 2
  - 0
  - 4
  - 1
  - 3
  Leg_room_service:
  - 4
  - 2
  - 3
  - 5
  - 1
  - 0
  On-board_service:
  - 4
  - 1
  - 5
  - 3
  - 2
  - 0
  Seat_comfort:
  - 4
  - 2
  - 3
  - 5
  - 1
  Type_of_Travel:
  - Business travel
  - Personal Travel
numerical_columns:
- Flight_Distance
