categorical_columns:
  Class:
  - Business
  - Eco Plus
  - Eco
  Customer_Type:
  - Loyal Customer
  - disloyal Customer
  Type_of_Travel:
  - Business travel
  - Personal Travel
numerical_columns:
- Flight_Distance
- Inflight_wifi_service
- Ease_of_Online_booking
- Seat_comfort
- Inflight_entertainment
- On-board_service
- Leg_room_service
- Cleanliness
